---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-backend
spec:
    replicas: {{ .Values.backend.replicas }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-backend
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-backend
        spec:
            containers:
                - name: {{ .Release.Name }}-backend
                  image: '{{ .Values.backend.image }}:{{ .Values.application.gitSHA }}'
                  command: ["uvicorn"]
                  args: ["app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "{{ .Values.backend.port }}"]
                  ports:
                      - containerPort: {{ .Values.backend.port }}
                  env:
                      - name: REDIS_URL
                        value: "redis://{{ .Release.Name }}-redis:{{ .Values.redis.port }}/0"
                      - name: BACKEND_PORT
                        value: "{{ .Values.backend.port }}"
                      - name: GIT_SHA
                        value: "{{ .Values.application.gitSHA }}"
                      - name: RELEASE_NAME
                        value: "{{ .Release.Name }}"
                      - name: SENTRY_DSN
                        valueFrom:
                          secretKeyRef:
                            name: {{ .Release.Name }}-secret-tokens
                            key: sentry-url
            imagePullSecrets:
                - name: {{ .Release.Name }}-dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-backend
spec:
    selector:
        app: {{ .Release.Name }}-backend
    ports:
        - port: {{ .Values.backend.port }}
