---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Release.Name }}-frontend
      port:
        number: {{ .Values.frontend.port }}
  rules:
    - host: {{ .Values.application.host }}
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.port }}
  tls:
    - hosts:
        - {{ .Values.application.host }}
      secretName: cloudflare-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-k8s-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_ssl_server_name on;
      proxy_ssl_name $host;
spec:
  ingressClassName: nginx
  rules:
    - host: "k8s.{{ .Values.application.host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443
  tls:
    - hosts:
        - "k8s.{{ .Values.application.host }}"
      secretName: cloudflare-tls
