---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret-tokens
type: Opaque
stringData:
    aws-access-key-id: "{{ .Values.application.secrets.awsAccessKeyId }}"
    aws-secret-access-key: "{{ .Values.application.secrets.awsSecretAccessKey }}"
    sentry-url: "{{ .Values.application.secrets.sentryUrl }}"
---
# https://dev.to/asizikov/using-github-container-registry-with-kubernetes-38fb
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dockerconfigjson-github-com
data:
  .dockerconfigjson: "{{ .Values.application.secrets.dockerConfigJson }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: {{ .Values.application.secrets.adminPassword }}
---
# cloudflare-tls secret with cert/pk files added manually
# https://nanjoran.com/2020/04/22/Kubernetes-Ingress-controller-with-Cloudflare/
